Name:           ros-kinetic-cmake-modules
Version:        0.4.1
Release:        0%{?dist}
Summary:        ROS cmake_modules package
Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz
Source1001:     %{name}.manifest
BuildRequires:  ros-kinetic-catkin
BuildRequires:  gcc-c++

%description
A common repository for CMake Modules which are not distributed with CMake but
are commonly used by ROS packages.

%prep
%setup -q
cp %{SOURCE1001} .

%build
%{__ros_setup}
%{__ros_build}

%install
%{__ros_setup}
%{__ros_install}

%files -f build/install_manifest.txt
%manifest %{name}.manifest
%defattr(-,root,root)

%changelog
* Thu Mar 30 2017 Zhang Xingtao <xingtao.zhang@yahoo.com> - 0.4.1
* Fri May 09 2014 William Woodall <william@osrfoundation.org> - 0.2.1-0
- Autogenerated by Bloom

